# Data structures

In [23]:
list = [1,3,4]
dictionary = {1: "One", 2: "Two", 3: "Three"} 
tuple = (1, 2, 3)
set = {1, 2, 3}

print("list:", list) 
print("dictionary:", dictionary) 
print("tuple:", tuple) 
print("set:", set)


list: [1, 3, 4]
dictionary: {1: 'One', 2: 'Two', 3: 'Three'}
tuple: (1, 2, 3)
set: {1, 2, 3}


# Useful Functions

In [22]:
#Length of list
list = [1,2,3]
print(len(list))
#String concatenation and int to string function
print(f'hi {len(list)}') # use format
print('hi ' + str(len(list)))
#Append/remove in list
list.append(4)
print(list)
list.remove(2)
print(list)
print(list.pop(1))
print(list)
#Count number in list
print(list.count(4))

# The help function can used on any other function to display its documentation
help(len)

3
hi 3
hi 3
[1, 2, 3, 4]
[1, 3, 4]
3
[1, 4]
1
Help on built-in function len in module builtins:

len(obj, /)
    Return the number of items in a container.



# Loops and conditions in Python 

In [22]:
for i in range(2):
    print(i)
    print(2-i)

i = 0
while i < len(range(2)):
    print(i)
    i += 1

0
2
1
1
0
1


In [8]:
# Conditions if and else are employed to nest conditions
x = 5
if x % 2 == 0:
    print('This is an even number.')
else:
    print('This is an odd number.')

This is an odd number.


# Functions

In [15]:
def hello(name):
    return 'hello ' + name
    
print(hello('Freddy'))

hello Freddy


# Numpy Arrays

In [23]:
## Import Numpy library - "as" keyword allows a simple reference to the package
import numpy as np

#1D zeros array
a = np.zeros(5)
print(a)
#2D zeros array
a = np.zeros([3,4])
print(a)

print('size:' + str(a.size))
print(f'size: {a.size}')
print('size:', a.size)
print('shape:' + str(a.shape))
print('Num dimensions:' + str(a.ndim))

# Arrays of ones can be made, and multipled by integers
b = 2*np.ones([3,4])
print(f'b: \n {b}')
print('a+b:')
print(a+b)

# Numpy range of numbers
print(np.arange(5,10))
# Can also be used with a step parameter
print('c:')
c = np.arange(5,10,0.5)
print(c)

# Elements from an array can be accessed using '[]'. Note: Python arrays index from 0
# Can also use slice
print(c[0])
print(c[1:3])

# Numpy arrays can be reshaped
print('d:')
d = b.reshape(2,6)
print(d)
print('shape', d.shape)

[0. 0. 0. 0. 0.]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
size:12
size: 12
size: 12
shape:(3, 4)
Num dimensions:2
b: 
 [[2. 2. 2. 2.]
 [2. 2. 2. 2.]
 [2. 2. 2. 2.]]
a+b:
[[2. 2. 2. 2.]
 [2. 2. 2. 2.]
 [2. 2. 2. 2.]]
[5 6 7 8 9]
c:
[5.  5.5 6.  6.5 7.  7.5 8.  8.5 9.  9.5]
5.0
[5.5 6. ]
d:
[[2. 2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2. 2.]]
shape (2, 6)


#  Pandas Dataframe

In [21]:
import pandas as pd

# create a simple dictionary of people
data = {
    'name': ['John','Anna', 'Peter', 'Linda'],
    'Location': ['New York', 'Paris', 'Berlin', 'London'],
    'age': [24, 13, 53 ,33]
}

# Convert dictionary to dataframe
data_pandas = pd.DataFrame(data)
# Ipython.display allows 'pretty printing' of dataframes
# in the Jupyter notebook
display(data_pandas)

# Specific columns of data can also be selected using '[]'
display(data_pandas[['name', 'age']])

# Rows an also be selected by either an integer of the row using the iloc function of pandas
display(data_pandas.iloc[[1,3]])

# You can also select a row with loc
# Let's first change the index of this dataset to 'Name', and then select the row for peter.
data_pandas = data_pandas.set_index('name')
display(data_pandas)
display(data_pandas.loc[['Peter']])

name  Location  age
0   John  New York   24
1   Anna     Paris   13
2  Peter    Berlin   53
3  Linda    London   33

name  age
0   John   24
1   Anna   13
2  Peter   53
3  Linda   33

name Location  age
1   Anna    Paris   13
3  Linda   London   33

Location  age
name                
John   New York   24
Anna      Paris   13
Peter    Berlin   53
Linda    London   33

Location  age
name               
Peter   Berlin   53